package Demo;
import javax.swing.*;
import java.awt.*;
public class GuiDemo {
public static void main(String args[]) {
	JFrame frame=new JFrame("WELCOME ");
	frame.setVisible(true);
	frame.setResizable(false);
	frame.setTitle("MY JFrames");
	//frame.setBounds(10, 10, 100, 50);
	Container c=frame.getContentPane();
	c.setLayout(null);
	//c.setBackground(Color.GREEN);
	//c.setBackground(Color.ORANGE);
	Font f=new Font("Arial",Font.BOLD,15);
	JLabel label=new JLabel("user label");
	label.setText("USERNAME:");
	label.setFont(f);
	c.add(label);
	JPasswordField pass=new JPasswordField();
	JLabel gender=new JLabel("GENDER :");
c.add(gender);
gender.setFont(f);
	JLabel lab=new JLabel("PASSWORD:");
	c.add(lab);
	lab.setFont(f);
	pass.setText("");
	pass.setFont(f);
	//pass.setBackground(Color.BLUE);
	c.add(pass);
	JButton b=new JButton();
	b.setText("LOGIN");
	c.add(b);
	JRadioButton jr=new JRadioButton();
	JRadioButton jr1=new JRadioButton();
	jr.setText("MALE");
	jr1.setText("FEMALE");
c.add(jr1);
	c.add(jr);
	JCheckBox cb=new JCheckBox();
	cb.setText("Accecpt Terms and Conditions");
	c.add(cb);
	//b.setBackground(Color.YELLOW);
//	jr.setBackground(Color.GREEN);
	//cb.setBackground(Color.GREEN);
	JTextField s=new JTextField();
	c.add(s);
	JLabel stu=new JLabel("STUDENT REGISTRATION SYSTEM");
	//stu.setText("");
	c.add(stu);
	Font fi=new Font("Arial",Font.BOLD,20);
	stu.setFont(fi);
	stu.setBounds(350, 10, 900, 100);
	gender.setBounds(400, 229, 900, 20);
	pass.setBounds(500,189, 100, 25);
	lab.setBounds(400,153,100,100);
	frame.setBounds(100, 100, 1000, 500);
	b.setBounds(450, 280, 100, 35);
	s.setBounds(500,157, 100, 25);
	label.setBounds(400, 150, 100, 40);
	cb.setBounds(400, 250, 200, 25);
	jr.setBounds(500, 229, 60, 20);
	jr1.setBounds(555, 229, 100, 20);

}}